import Layout from '@/components/layout/Layout'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <html lang='en'>
      <head>
        <title>eCommerce</title>
        <script
          type='module'
          crossOrigin='true'
          src='https://assets.conekta.com/component/3.3.3/assets/component.min.js'
        />
      </head>
      <body>
        <Layout />
        <div>{children}</div>
      </body>
    </html>
  )
}
